### PR TITLE
Sync auxpow

### PR DESCRIPTION
**Pull request by mmicael1**

### CODE REVIEW

**Comment by rnicoll** [comment]
I'm not sure the changes to the Scrypt code are worth doing, they'll change the `git blame` lines on a lot of things, and we tend not to touch that code honestly. I also want to try fixing the circular dependencies by removing the dependencies, if I can, so going to hold off on that.

For the rest, can you raise them as a PR against https://github.com/dogecoin/dogecoin/tree/1.21-dev/ please? We should be able to get most of them merged in while the AuxPoW work continues, and as they'll be a smaller PR it will be easier to review.

Thanks!

**Comment by rnicoll** [comment]
I've manually pulled most of your commits in, if you can do a rebase of https://github.com/rnicoll/dogecoin/pull/19/commits/15b43c506ecf38a7f96692c1d9e6dd7ead8ea275 against dogecoin/dogecoin but without the scrypt changes, I think we can merge this in by itself, and this will then get bundled in when we merge the AuxPoW work.

Thanks!

**Comment by mmicael1** [comment]
> 15b43c5

@rnicoll Not sure the rebase against dogecoin/dogecoin will worked as this PR is based on your PR sync-auxpow

**Comment by rnicoll** [comment]
> 
> 
> > [15b43c5](https://github.com/rnicoll/dogecoin/commit/15b43c506ecf38a7f96692c1d9e6dd7ead8ea275)
> 
> @rnicoll Not sure the rebase against dogecoin/dogecoin will worked as this PR is based on your PR sync-auxpow

I _think_ all of the whitespace corrections apply to code that's already merged as of last night, but let me know if not.

**Comment by rnicoll** [comment]
I've had to do a rebase as part of cleanup, but cherry-picked this in manually, thanks!

**Pull request closed without merging**
