### PR TITLE
[DRAFT] Rework readme for contribution guideline

### PR DESCRIPTION
**Pull request by AbcSxyZ**
Redo the readme, make it easier/shorter and less developer focused.
Keep more general info, redirect more to other file to reduce the amount of infos.

[Not sure if it's the best way to push commits, I'm struggling with git to add commit to a PR where I do not have rights on the repo]

PS.: Not a native english speaker (you probably already saw it I think),  perhaps some sentences construction are bad.

### CODE REVIEW

**Comment by rnicoll** [comment]
Given scale (this is a lot more changes than the PR it merges into), I'm inclined to suggest it is a PR after mine. Let me see what Patrick's feedback is, as he's got comments incoming.

Also I'm not sure linking developer resources into the README is a good idea, we already get a lot of people using these as support channels, which we're not equipped for.

**Comment by AbcSxyZ** [comment]
Developer resources in the `Ongoing development - Moon plan` section ?

Developpement are important to be accessible even for non devs user. To know/understand and potentially participate in some decision. For exemple, some other user than devs should be aware of fees change, they are also concerned.

An interface have to be done for sure, but ongoing devs should be easily accessible for the outside.

**Comment by rnicoll** [comment]
I've rebased this and pushed the result into a branch https://github.com/rnicoll/dogecoin/tree/contributing - can you grab a copy of that, check it's okay, and then raise it against dogecoin/dogecoin for the team to review please?

**Comment by AbcSxyZ** [comment]
I will wait a couple of day if I have some reactions to my different [post](https://www.reddit.com/r/dogecoindev/comments/nvrnyi/docs4doge_initiative_update_the_dogecoin/) and [issue](https://github.com/dogecoin/dogecoin/issues/2271) before push on Dogecoin repo.

Like I said I thought it was more interesting to first define an accepted (or not rejected) roadmap, and after do some work.
I do not PR too fast to be coherent & to try to involve potential contributors in the process :)

**Pull request closed without merging**
